version: '3.1'
services:
  stats-server:
    build: ./stats/server
    container_name: stats_server
    ports:
      - "9090:9090"
    depends_on:
      - ewm-stats-db
    environment:
      - DB_HOST=ewm_stats_db
      - DB_PORT=5432
      - DB_NAME=statsdb
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm_pwd

  ewm-stats-db:
    image: postgres:14-alpine
    container_name: ewm_stats_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statsdb
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm_pwd

  ewm-service:
    build: ./main
    container_name: ewm_service
    depends_on:
      - ewm-db
      - ewm-stats-server
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=ewm_db
      - DB_PORT=5432
      - DB_NAME=main_service_db
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm_pwd
      - STATS_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm_db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=main_service_db
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm_pwd
