CREATE TABLE IF NOT EXISTS endpoint_hits
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
    app       VARCHAR(128)                                           NOT NULL,
    uri       VARCHAR(2128)                                         NOT NULL,
    ip        VARCHAR(64)                                           NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_endpoint_hit PRIMARY KEY (id)
);
